/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITind3rMatching } from "./ITind3rMatching";
export type { ITind3rMembership } from "./ITind3rMembership";
export type { Tind3rMatching } from "./Tind3rMatching";
export type { Tind3rMembership } from "./Tind3rMembership";
